## Using Logistic Regression to predict

In [1]:
import numpy as np
import pandas as pd

pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  
0               30          0         2     1                          4  
1               31          0         1     0                          0  
2               31          0         0     0                          2  
3               24          0         2     0                          4  
4               30          0         2     1                          2

In [3]:
#Using median as a cutoff line is numerrically stable and rigid, Using median we implicitly balances the data set.
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

###### As the median of the absenteeism time is 3.0 hours, any thing below that is Moderately Absent we'll assign it a value 0, any thing above that is Excessively absent we'll assine it a value 1. In supervised learning we call these 0's and 1's targets.

In [4]:
#parametrization easy to understand and follow. Also minimizes the chances of making mistake
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                   data_preprocessed['Absenteeism Time in Hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [5]:
data_preprocessed['Excessive Absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [6]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [7]:
data_preprocessed.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets', 'Absenteeism Time in Hours',
       'Excessive Absenteeism'], dtype=object)

In [8]:
data_with_targets = data_preprocessed.drop(['Day of the Week', 'Distance to Work',
                                            'Daily Work Load Average', 'Absenteeism Time in Hours'], axis=1)

In [9]:
#True-> the two variables refer to the same object. False-> Two variable refer to different objects.
data_with_targets is data_preprocessed

False

## Select the inputs for the regression

In [10]:
data_with_targets.shape

(700, 12)

In [11]:
#data_with_targets.iloc[:,:14]
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
5           0         0         0         1            7   
6           0         0         0         1            7   
7           0         0         0         1            7   
8           0         0         1         0            7   
9           0         0         0         1            7   
10          1         0         0         0            7   
11          1         0         0         0            7   
12          1         0         0         0            7   
13          1         0         0         0            7   
14          0         0         0         1            7   
15          1         0         0         0            7   
16          0         0         0         1            7   
17          0         0         1         0            7   
18          1         0         0         0            7   
19          0         0         0         1            8   
20          1         0         0         0            8   
21          1         0         0         0            8   
22          1         0         0         0            8   
23          0         0         0         1            8   
24          0         0         1         0            8   
25          0         0         0         1            8   
26          0         0         0         1            8   
27          0         0         0         1            8   
28          0         0         1         0            8   
29          0         0         0         1            8   
30          0         0         1         0            8   
31          0         0         1         0            8   
32          0         0         0         1            8   
33          0         0         1         0            8   
34          0         0         0         1            8   
35          0         0         0         1            8   
36          0         0         0         1            8   
37          1         0         0         0            8   
38          0         0         0         1            8   
39          0         0         0         1            8   
40          0         0         0         1            9   
41          0         0         0         1            9   
42          0         0         0         1            9   
43          0         0         1         0            9   
44          0         0         0         1            9   
45          0         0         0         1            9   
46          0         0         0         1            9   
47          0         0         0         1            9   
48          0         0         0         1            9   
49          1         0         0         0            9   
50          0         0         0         0            9   
51          0         0         0         0            9   
52          0         0         0         1            9   
53          0         0         0         1            9   
54          0         0         0         0            9   
55          0         0         0         0            9   
56          0         0         1         0            9   
57          0         0         0         1            9   
58          0         0         0         0            9   
59          0         0         0         1            9   
60          0         0         0         1            9   
61          0         0         0         1            9   
62          0         0         0         1           10   
63          0         0         0         1           10   
64          0         0         0         0           10   
65          0         0         0         1  

In [12]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the data

In [13]:
#from sklearn.preprocessing import StandardScaler
#absenteeism_scaler = StandardScaler()

In [14]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):

    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std) #(copy, with_mean, with_std)
        self.columns = columns
        self.mean_ = None
        self.std_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns, index=X.index)
        #X_not_scaled = X.loc[:, ~Xcolumns.isin(seld.columns)]
        X_not_scaled = X.drop(columns=self.columns, axis=1)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [15]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [16]:
#columns_to_scaled = ['Month Value', 'Day of the Week', 'Transportation Expense', 'Distance to Work',
#       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Children', 'Pets']

columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Education']

In [17]:
columns_to_scaled = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]
columns_to_scaled

['Month Value',
 'Transportation Expense',
 'Age',
 'Body Mass Index',
 'Children',
 'Pets']

In [18]:
absenteeism_scaler = CustomScaler(columns_to_scaled)

In [19]:
absenteeism_scaler.fit(unscaled_inputs)

C:\Users\10may\AppData\Roaming\Python\Python310\site-packages\numpy\core\fromnumeric.py:3785: FutureWarning: The behavior of DataFrame.var with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return var(axis=axis, dtype=dtype, out=out, ddof=ddof, **kwargs)


AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

AttributeError: 'CustomScaler' object has no attribute 'copy'

In [20]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [21]:
scaled_inputs

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1     0.182726   
1           0         0         0         0     0.182726   
2           0         0         0         1     0.182726   
3           1         0         0         0     0.182726   
4           0         0         0         1     0.182726   
5           0         0         0         1     0.182726   
6           0         0         0         1     0.182726   
7           0         0         0         1     0.182726   
8           0         0         1         0     0.182726   
9           0         0         0         1     0.182726   
10          1         0         0         0     0.182726   
11          1         0         0         0     0.182726   
12          1         0         0         0     0.182726   
13          1         0         0         0     0.182726   
14          0         0         0         1     0.182726   
15          1         0         0         0     0.182726   
16          0         0         0         1     0.182726   
17          0         0         1         0     0.182726   
18          1         0         0         0     0.182726   
19          0         0         0         1     0.468236   
20          1         0         0         0     0.468236   
21          1         0         0         0     0.468236   
22          1         0         0         0     0.468236   
23          0         0         0         1     0.468236   
24          0         0         1         0     0.468236   
25          0         0         0         1     0.468236   
26          0         0         0         1     0.468236   
27          0         0         0         1     0.468236   
28          0         0         1         0     0.468236   
29          0         0         0         1     0.468236   
30          0         0         1         0     0.468236   
31          0         0         1         0     0.468236   
32          0         0         0         1     0.468236   
33          0         0         1         0     0.468236   
34          0         0         0         1     0.468236   
35          0         0         0         1     0.468236   
36          0         0         0         1     0.468236   
37          1         0         0         0     0.468236   
38          0         0         0         1     0.468236   
39          0         0         0         1     0.468236   
40          0         0         0         1     0.753746   
41          0         0         0         1     0.753746   
42          0         0         0         1     0.753746   
43          0         0         1         0     0.753746   
44          0         0         0         1     0.753746   
45          0         0         0         1     0.753746   
46          0         0         0         1     0.753746   
47          0         0         0         1     0.753746   
48          0         0         0         1     0.753746   
49          1         0         0         0     0.753746   
50          0         0         0         0     0.753746   
51          0         0         0         0     0.753746   
52          0         0         0         1     0.753746   
53          0         0         0         1     0.753746   
54          0         0         0         0     0.753746   
55          0         0         0         0     0.753746   
56          0         0         1         0     0.753746   
57          0         0         0         1     0.753746   
58          0         0         0         0     0.753746   
59          0         0         0         1     0.753746   
60          0         0         0         1     0.753746   
61          0         0         0         1     0.753746   
62          0         0         0         1     1.039256   
63          0         0         0         1     1.039256   
64          0         0         0         0     1.039256   
65          0         0         0         1  

In [22]:
scaled_inputs.shape

(700, 11)

## Spliting the data into Training & Testing and shuffle

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
train_test_split(scaled_inputs, targets)
#It contains 4 arrays
#array 1-> Training dataset with inputs
#array 2-> Training dataset with targets
#array 3-> Test dataset with inputs
#array 4-> Test dataset with targets

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 385         0         0         0         1    -1.244823   
 613         0         0         0         1    -1.244823   
 574         1         0         0         0    -1.530333   
 277         0         0         0         0     0.753746   
 296         1         0         0         0     1.039256   
 322         1         0         0         0     1.324766   
 133         0         0         0         1    -1.530333   
 493         0         0         0         1     0.468236   
 558         1         0         0         0     1.610276   
 629         0         0         1         0    -0.959313   
 584         0         0         0         1    -1.530333   
 291         0         0         0         1     1.039256   
 525         1         0         0         0     1.039256   
 314         1         0         0         0     1.039256   
 646         0         0         0         1    -0.959313   
 9           0         0

In [25]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size=0.8, random_state=20)

In [26]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [27]:
print( x_test.shape, y_test.shape)

(140, 11) (140,)


## Logistic Regression with sklearn

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Train the model

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

LogisticRegression()

In [31]:
reg.score(x_train, y_train)

0.7732142857142857

### Manually checking the accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum((model_outputs == y_train))

433

In [36]:
model_outputs.shape

(560,)

In [37]:
np.sum((model_outputs == y_train)) / model_outputs.shape[0]

0.7732142857142857

### Intercept & Cofficients

In [38]:
reg.intercept_

array([-1.6474549])

In [39]:
reg.coef_

array([[ 2.80019733,  0.95188356,  3.11555338,  0.83900082,  0.1589299 ,
         0.60528415, -0.16989096,  0.27981088, -0.21053312,  0.34826214,
        -0.27739602]])

In [40]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_tabel = pd.DataFrame(columns=['Feature name'], data=feature_name)

summary_tabel['Coefficient'] = np.transpose(reg.coef_) #We have to trasnpose the array as by default the ND arrays are rows not columns.

summary_tabel

Feature name  Coefficient
0                 Reason_1     2.800197
1                 Reason_2     0.951884
2                 Reason_3     3.115553
3                 Reason_4     0.839001
4              Month Value     0.158930
5   Transportation Expense     0.605284
6                      Age    -0.169891
7          Body Mass Index     0.279811
8                Education    -0.210533
9                 Children     0.348262
10                    Pets    -0.277396

In [43]:
summary_tabel.index = summary_tabel.index + 1
summary_tabel.loc[0] = ['Intercept', reg.intercept_[0]]
summary_tabel = summary_tabel.sort_index()
summary_tabel

Feature name  Coefficient
0                Intercept    -1.647455
1                 Reason_1     2.800197
2                 Reason_2     0.951884
3                 Reason_3     3.115553
4                 Reason_4     0.839001
5              Month Value     0.158930
6   Transportation Expense     0.605284
7                      Age    -0.169891
8          Body Mass Index     0.279811
9                Education    -0.210533
10                Children     0.348262
11                    Pets    -0.277396

In [44]:
summary_tabel['Odds Ratio'] = np.exp(summary_tabel['Coefficient'])
summary_tabel

Feature name  Coefficient  Odds Ratio
0                Intercept    -1.647455    0.192539
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
3                 Reason_3     3.115553   22.545903
4                 Reason_4     0.839001    2.314054
5              Month Value     0.158930    1.172256
6   Transportation Expense     0.605284    1.831773
7                      Age    -0.169891    0.843757
8          Body Mass Index     0.279811    1.322880
9                Education    -0.210533    0.810152
10                Children     0.348262    1.416604
11                    Pets    -0.277396    0.757754

In [45]:
summary_tabel.sort_values('Odds Ratio', ascending=False) #by default it is in ascending order

Feature name  Coefficient  Odds Ratio
3                 Reason_3     3.115553   22.545903
1                 Reason_1     2.800197   16.447892
2                 Reason_2     0.951884    2.590585
4                 Reason_4     0.839001    2.314054
6   Transportation Expense     0.605284    1.831773
10                Children     0.348262    1.416604
8          Body Mass Index     0.279811    1.322880
5              Month Value     0.158930    1.172256
7                      Age    -0.169891    0.843757
9                Education    -0.210533    0.810152
11                    Pets    -0.277396    0.757754
0                Intercept    -1.647455    0.192539

###### If a coefficient is around 0 or its odds are close to 1 this means the corresponding feature is not perticularly important.
###### Because a weight of 0 implies that no matter the feature value, we will multiply it by 0.
###### For one unit change in the standardized feature, the odds increase by a multiple equal to the odds ratio(1=no change).
###### Odds X Odds Ratio = New Odds (ex-> 5:1 X 1 = 5:1(no change))

## Backward Elimination
###### The idea is that we can simplify our model by removing all features which has close to no contribution to the model.
###### When we have the p-value, we get rid off all coefficients with p-value>0.05
###### When learning with sklearn, we dont have p-value because we dont necessarily need them.
###### The reasoning is that if the weight is small enough it wont make a difference anyways.
###### If we remove these variables, the rest of our model should not really change in terms of coefficient values.

## Testing the model

In [46]:
reg.score(x_test, y_test)

0.75

In [47]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba
# Returns the prob estimates for all possible outputs(class)
# 1st colums shows the prob our model assigned to the observation bring 0. 2nd the prob our model assigned to the obs. being 1.

array([[0.71340413, 0.28659587],
       [0.58724228, 0.41275772],
       [0.44020821, 0.55979179],
       [0.78159464, 0.21840536],
       [0.08410854, 0.91589146],
       [0.33487603, 0.66512397],
       [0.29984576, 0.70015424],
       [0.13103971, 0.86896029],
       [0.78625404, 0.21374596],
       [0.74903632, 0.25096368],
       [0.49397598, 0.50602402],
       [0.22484913, 0.77515087],
       [0.07129151, 0.92870849],
       [0.73178133, 0.26821867],
       [0.30934135, 0.69065865],
       [0.5471671 , 0.4528329 ],
       [0.55052275, 0.44947725],
       [0.5392707 , 0.4607293 ],
       [0.40201117, 0.59798883],
       [0.05361575, 0.94638425],
       [0.7003009 , 0.2996991 ],
       [0.78159464, 0.21840536],
       [0.42037128, 0.57962872],
       [0.42037128, 0.57962872],
       [0.24783565, 0.75216435],
       [0.74566259, 0.25433741],
       [0.51017274, 0.48982726],
       [0.85690195, 0.14309805],
       [0.20349733, 0.79650267],
       [0.78159464, 0.21840536],
       [0.

In [48]:
predicted_proba.shape

(140, 2)

In [49]:
# We are interested in prob of excessive absenteeism, so the prob of getting one.
predicted_proba[:, 1]

array([0.28659587, 0.41275772, 0.55979179, 0.21840536, 0.91589146,
       0.66512397, 0.70015424, 0.86896029, 0.21374596, 0.25096368,
       0.50602402, 0.77515087, 0.92870849, 0.26821867, 0.69065865,
       0.4528329 , 0.44947725, 0.4607293 , 0.59798883, 0.94638425,
       0.2996991 , 0.21840536, 0.57962872, 0.57962872, 0.75216435,
       0.25433741, 0.48982726, 0.14309805, 0.79650267, 0.21840536,
       0.36956558, 0.67906035, 0.68502567, 0.52868083, 0.21840536,
       0.53506551, 0.22147081, 0.73692105, 0.40498044, 0.60505988,
       0.21075848, 0.45224466, 0.23751292, 0.39833498, 0.82755447,
       0.56797575, 0.69113325, 0.28659587, 0.21935267, 0.2033097 ,
       0.57628256, 0.3294664 , 0.66512397, 0.26949499, 0.83321968,
       0.43491525, 0.88374612, 0.23127072, 0.33415858, 0.34432939,
       0.69909345, 0.65494263, 0.29244941, 0.79200758, 0.20750276,
       0.26840558, 0.08708566, 0.22147081, 0.73245417, 0.30530219,
       0.22147081, 0.29014408, 0.90438191, 0.46061297, 0.60174

###### In reality, logistic reg model calculate these prob in the background.
###### If prob is below 0.5, it places a 0. above 0.5, it places a 1

# Save the model

In [50]:
#pickle is a python module use to convert a python object into a character stream.
import pickle

In [51]:
with open('model', 'wb') as file: #'model'-> file name. 'wb'-> write bytes. when we unpickle we use 'rb' read bytes.
    pickle.dump(reg, file) #dump ->when we pickle, we dump the info in a file. Whne we unpickle, we lode it. object to be dumped and python syntax.

In [52]:
with open('scaler', 'wb') as file:
    pickle.dump(absenteeism_scaler, file)